### ISSUE TITLE
Does not seem to work in the latest VSCode

### ISSUE THREAD

**Issue by jooyoungseo** [ogomez92/indent_reporter_vscode#1]
## System Info

Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

## Current Issue

After installing this extension, I have tested the following Python code. However, it does not seem to work because I don't hear any sounds.

``` python
def test():
    pass
        print("Hello worl!")
```

**Comment by ogomez92** [comment]
Hello.
This extension currently works only on macOS. On Windows, please use NVDA's indentation by tones. You can find it in preferences.

For macOS there is a more recent and probably better alternative now, please check this one out.
https://github.com/pitermach/IndentBeeper

This works on any text field.
